### ISSUE TITLE
3D sound is too low

### ISSUE THREAD

**Issue by chingachgook** [jhakonen/wot-teamspeak-mod#19]
If you turn 3D sound (HRTF), the voice becomes low, distorted.

**Comment by jhakonen** [comment]
Hi chingachgook,

Have you changed the "Voice Volume Adjustment" slider in Options > Playback?

OpenAL may clamp any volume increase above 0 dB, so if you have the slider set over 0, the 3D positioned audio may sound lower than normal non-positioned audio.

Also, I haven't actually tested the 3D feature with 2 or more players. Is there any difference in volume level when there are more players in team (3-man platoon, skirmish, etc...)?

You can also have positioned audio without HRTF, it just isn't as 3D-ish. You can even switch to use TeamSpeak's own internal positioning audio engine if all else fails.

Note also that the 3D feature is still in alpha phase, so there is likely bugs in it and missing functionality.

**Comment by chingachgook** [comment]
Sorry for my english, low is "pitched down", not low volume.
With 2 or more players is no difference.

**Comment by jhakonen** [comment]
Hi, sorry for delay.
I think I have finally managed to fix the issue.
I've made a test release for you, can you verify that it works?

Here's the archive:
https://dl.dropboxusercontent.com/u/37902077/wot/tessu_mod/issue-19/tessumod-0.6.1-test-issue-19-bin.zip

If you have 0.6.1 already installed then you only need to update the teamspeak plugin.

**Comment by chingachgook** [comment]
Fixed.

**Comment by jhakonen** [comment]
Ok, awesome!

This has also been fixed to master-branch in commit 475f55ca234e8ca52cf0c3e870cf2f5c926db6dd.

Marking the issue closed.
