### ISSUE TITLE
Cant seem to get it to work in 9.7 

### ISSUE THREAD

**Issue by beals1pt0** [jhakonen/wot-teamspeak-mod#20]
i have used this mod since your first release and for some reason it is not working for me on the latest patch I am not getting the notifications of even trying to connect to ts3. is there a list of mods that may conflict with this ?

**Comment by beals1pt0** [comment]
never mind I noticed I had client query turned off on my ts3 client all is working as intended

**Comment by jhakonen** [comment]
Yup, that indeed would cause it :)

Closing the issue.
