### ISSUE TITLE
Build plugin for TeamSpeak 3.1 beta

### ISSUE THREAD

**Issue by jhakonen** [jhakonen/wot-teamspeak-mod#26]
TeamSpeak has a new version incoming. 3.1 is currently in beta phase.
This was reported by ChrTok at http://aslain.com/index.php?/topic/6852-tessumod-incompatible/

TeamSpeak 3.1 Release notes and feedback thread: 
http://forum.teamspeak.com/threads/126565-Discussion-TeamSpeak-3-Client-3-1-BETA

TeamSpeak plugin interface changes:
https://github.com/svenpaulsen/ts3client-pluginsdk/compare/aa05106be6345d7dd7edf4716330bce5adff3563...db1fc56f55de51f258e30b04e3637b5e8d32af9a

The new version is build with Visual Studio 2015.

To support the new version we should have a separate feature branch which contains changes:
- Install Visual Studio 2015 (instead of 2013)
- Build Qt and OpenAl Soft with VS2015.
- Update TeamSpeak's Plugin SDK
- Whatever code changes needed to make the plugin compile and behave nicely

Might be best to release the plugin as a separate download and instruct users to install that one instead of the plugin distributed within mod's archive if they have TeamSpeak 3.1 installed.

Integrate the feature branch back to master when TeamSpeak releases the 3.1 to stable channel.

**Comment by Miscni** [comment]
Been looking it over, and I am getting issues on OBC and OBS, I would gladly admit, that it could be a error 39½ from my side.

**Comment by jhakonen** [comment]
Hi Miscni,

What is OBC or OBS?

**Comment by Miscni** [comment]
your code is being use here
https://obsproject.com/forum/resources/teamspeak-3-plugin.40/  (Open Broadcaster Classic)
and
https://obsproject.com/forum/resources/teamspeak-3-studio-plugin.448/ (Open Broadcaster Studio)
it is your code there is being used.

**Comment by jhakonen** [comment]
Umm, I think you have wrong plugin. The OBS refers to this project:
https://github.com/adocilesloth/TS3StudioPlugin

**Comment by Miscni** [comment]
I know, but I was refered into here, because some of the base code, was from your work

**Comment by jhakonen** [comment]
I think there is some kind of mixup. The Tessumod doesn't have really anything to do with OBS. I checked the code of two plugins, but I don't see anything even closely familiar about them. They are plugins to OBS, while the plugin related to this issue is a plugin to Teamspeak. They don't really have anything in common.

**Comment by Miscni** [comment]
hmmm.... Dont understand it then, oh well then I just have to go back to the drawing board, and see if I can fix the overlay. Just needed the overlay either from ts or OBS.
Sorry for takeing your time mate. Cheers
PS. Let me know, if you need some promo

**Comment by jhakonen** [comment]
There's already support for TeamSpeak 3.3.0, so closing this as obsolete.
