### ISSUE TITLE
Any Linux How-to?

### ISSUE THREAD

**Issue by bertalanimre** [jhakonen/wot-teamspeak-mod#30]
I'M playing WoT on Linux and I wish to install this mod on it somehow. But unfortunately I can'T make TS recognize the TessuMod as plugin? Can somebody help me with it?

**Comment by jhakonen** [comment]
Hi bertalanimre,

Have you tried running TeamSpeak under Wine?

The plugin doesn't have native Linux binary, so it will not load to native TeamSpeak. You might have better luck running TeamSpeak under Wine, in which case the plugin might also load. I haven't tested it under Wine though, so can't promise that it works.

**Comment by bertalanimre** [comment]
I was able to make TS recognise the plugin simply by renaming the dll files to so files. Then TS recognized the plugin and it started working. :) If you want, I can write a step-by-step guide how to make it working. Luckily I didn't have to use wine for it, it runs on native Linux TS.

**Comment by jhakonen** [comment]
Intresting, I gave it a whack too. I installed Ubuntu 17.10 to a virtual machine, installed native TeamSpeak, extracted tessumod plugin to TS's plugins folder and renamed dll to so.

But, it didn't work for me though:
```
2017-11-27 17:25:25.186035|INFO    |Plugins       |   |Loading plugin: tessumod_plugin_x64.so
2017-11-27 17:25:25.188039|INFO    |Plugins       |   |Failed to load plugin: /home/jhakonen/.ts3client/plugins/tessumod_plugin_x64.so
2017-11-27 17:25:25.188131|INFO    |Plugins       |   |dlopen error: /home/jhakonen/.ts3client/plugins/tessumod_plugin_x64.so: invalid ELF header
```

**Comment by bertalanimre** [comment]
It works for me on World of Tanks. But only in a game. In the lobby it works only if somebody has the exact same nickname as in the game. copied the plugin to world of tanks folder and the plugins to teamspeak. It shows as incorrect, but somehow it still works

**Comment by jhakonen** [comment]
Oh, in that case the plugin most likely didn't actually load at all.

The mod works without the TS plugin though. Without the plugin you will not have positional audio, but otherwise the mod should work fine.

**Comment by bertalanimre** [comment]
Aggreed
