### ISSUE TITLE
Many errors

### ISSUE THREAD

**Issue by Suvero** [jhakonen/wot-teamspeak-mod#34]
Hello ! I compiled this mod as in description but mod after install into wot mods folder, not working. Your compiled file working but compiled by me, not. I tried suite test but (screenshot)...

WoT in python.log too giving some errors as in screenshoot too.
![error](https://user-images.githubusercontent.com/44507538/65766525-915ac880-e12b-11e9-9ca6-7d7c8afc2256.PNG)

Thanks for help ! I wanna remake this mod for my clan with Your copyright of course :)

**Comment by Suvero** [comment]
* Python 3.7 installed *

**Comment by Suvero** [comment]
Additionally, my file weight 296kb but Your original around ~310kb as I remember..

**Comment by jhakonen** [comment]
Hi Suvero!

You're welcome to fork it!
Just comply with the license and I don't have anything to complain about :)

The file at test/fute/__init__.py is empty in master branch, so it shouldn't fail. As such I assume you're either in the fixes-0.7 branch or at the 0.7.1 tag, right? Unfortunately those don't yet support Python 3.7, support for it is in the master branch only. You would need to use Python 2.7 instead.

And uh, looks like I've forgotten to merge the 0.7.1's fix for WoT 1.6.0.2 to the master branch, so that branch isn't working at the moment (in game). I'll see if I can merge the fix to master ASAP. Otherwise the master should be stable, if you wish to continue with Python 3.7.

Building the wotmod file with wrong Python version could be one reason why the game will not load it and could explain the size difference.

**Comment by Suvero** [comment]
If I compiling wotmod using 2.7, it is clear (0 errors) but the weight is the same (296kb) and it not loading into wot too.

**Comment by jhakonen** [comment]
Hmm, that's weird. Can you attach the wotmod file? I can take a look at it.

**Comment by Suvero** [comment]
Of course, please -> https://www.icloud.com/iclouddrive/0neqV7TAW71iG7bWS6Vc36R5g#jhakonen.tessumod%5F00.07.01

**Comment by jhakonen** [comment]
Looks like your wotmod did work in 1.6.0.2. However, the mod doesn't seem to work in 1.6.0.8 anymore.
The size difference seems to be mainly because each pyc file contain path to the original py file, and the paths in your pyc files seems to have shorter paths for some reason.

Here's for example the tessumod/\_\_init__.py's compiled version:
```
$ hexdump -C /tmp/tessumod-suvero/res/scripts/client/gui/mods/tessumod/__init__.pyc
00000000  03 f3 0d 0a 03 40 62 5d  63 00 00 00 00 00 00 00  |.....@b]c.......|
00000010  00 01 00 00 00 40 00 00  00 73 04 00 00 00 64 00  |.....@...s....d.|
00000020  00 53 28 01 00 00 00 4e  28 00 00 00 00 28 00 00  |.S(....N(....(..|
00000030  00 00 28 00 00 00 00 28  00 00 00 00 73 14 00 00  |..(....(....s...|
00000040  00 74 65 73 73 75 6d 6f  64 2f 5f 5f 69 6e 69 74  |.tessumod/__init|
00000050  5f 5f 2e 70 79 74 08 00  00 00 3c 6d 6f 64 75 6c  |__.pyt....<modul|
00000060  65 3e 01 00 00 00 73 00  00 00 00                 |e>....s....|
0000006b
$ hexdump -C /tmp/tessumod-jhakonen/res/scripts/client/gui/mods/tessumod/__init__.pyc
00000000  03 f3 0d 0a e1 81 20 5d  63 00 00 00 00 00 00 00  |...... ]c.......|
00000010  00 01 00 00 00 40 00 00  00 73 04 00 00 00 64 00  |.....@...s....d.|
00000020  00 53 28 01 00 00 00 4e  28 00 00 00 00 28 00 00  |.S(....N(....(..|
00000030  00 00 28 00 00 00 00 28  00 00 00 00 73 31 00 00  |..(....(....s1..|
00000040  00 2f 72 65 73 2f 73 63  72 69 70 74 73 2f 63 6c  |./res/scripts/cl|
00000050  69 65 6e 74 2f 67 75 69  2f 6d 6f 64 73 2f 74 65  |ient/gui/mods/te|
00000060  73 73 75 6d 6f 64 2f 5f  5f 69 6e 69 74 5f 5f 2e  |ssumod/__init__.|
00000070  70 79 74 08 00 00 00 3c  6d 6f 64 75 6c 65 3e 01  |pyt....<module>.|
00000080  00 00 00 74 00 00 00 00                           |...t....|
00000088
```
In addition, your wotmod doesn't have build_info.pyc which I think causes these errors in the log:
```
2019-09-28 21:31:14.294: ERROR: [EXCEPTION] (scripts/common/Event.py, 46):
Traceback (most recent call last):
  File "scripts/common/Event.py", line 44, in __call__
  File "mod_tessumod.py", line 265, in on_connected_to_ts3
  File "mod_tessumod.py", line 282, in handle_plugin_info
  File "mod_tessumod.py", line 325, in get_plugin_advertisement_info
  File "mod_tessumod.py", line 377, in parse_version
AssertionError

2019-09-28 21:31:14.299: ERROR: [EXCEPTION] (scripts/common/Event.py, 46):
Traceback (most recent call last):
  File "scripts/common/Event.py", line 44, in __call__
  File "tessumod/ts3.py", line 152, in check_events
  File "tessumod/statemachine.py", line 81, in tick
  File "tessumod/statemachine.py", line 49, in transit
  File "scripts/common/Event.py", line 44, in __call__
  File "mod_tessumod.py", line 265, in on_connected_to_ts3
  File "mod_tessumod.py", line 282, in handle_plugin_info
  File "mod_tessumod.py", line 325, in get_plugin_advertisement_info
  File "mod_tessumod.py", line 377, in parse_version
AssertionError
```
However, those do not prevent the mod from working. And your wotmod file worked fine with 1.6.0.2, despite of the errors. So, I think there's some incompatibility with most recent WoT's version. I'll try to fix that.

**Comment by Suvero** [comment]
But Your version working on latest version fine... how ? Why source code not working if release working ?

**Comment by jhakonen** [comment]
No, actually scratch that. The reason why your wotmod doesn't work is that it missing the build_info.pyc file. I just don't know why it worked when I tried it with 1.6.0.2.

Unfortunately I don't know why the build_info.pyc would be missing. I tried with clean working copy  and recreated the wotmod file, but the pyc file generated just fine for me.

**Comment by jhakonen** [comment]
You could try adding some debug printing to figure out why the build_info.pyc doesn't appear.

Add these lines to setup.py:
```
import distutils.command.build_py
original_build_py_copy_file = distutils.command.build_py.build_py.copy_file
def printing_copy_file(self, *args, **kwargs):
    print "copy_file:", args, kwargs
    return original_build_py_copy_file(self, *args, **kwargs)
distutils.command.build_py.build_py.copy_file = printing_copy_file
```
Then print where the build_info.py is output, by adding print command to setup_helpers.py at line 28, like this:
```
...
						with open(outfile, 'w') as output_file:
							print "Generate in file:", module_file, "-->", outfile
							output_file.write(input_file.read().format(**options))
...
```
Finally, in setup.cfg change `verbose=0` to `verbose=1`.

Here's what I get when running the bdist_wotmod:
```
$ ./setup.py bdist_wotmod
running bdist_wotmod
running build
running build_py
Generate in file: src/tessumod/build_info.py.in --> build/lib.linux-x86_64-2.7/tessumod/build_info.py
copy_file: ('src/mod_tessumod.py', 'build/lib.linux-x86_64-2.7/mod_tessumod.py') {'preserve_mode': 0}
copy_file: ('src/tessumod/user_cache.py', 'build/lib.linux-x86_64-2.7/tessumod/user_cache.py') {'preserve_mode': 0}
copy_file: ('src/tessumod/ts3.py', 'build/lib.linux-x86_64-2.7/tessumod/ts3.py') {'preserve_mode': 0}
copy_file: ('src/tessumod/keyvaluestorage.py', 'build/lib.linux-x86_64-2.7/tessumod/keyvaluestorage.py') {'preserve_mode': 0}
copy_file: ('src/tessumod/positional_audio.py', 'build/lib.linux-x86_64-2.7/tessumod/positional_audio.py') {'preserve_mode': 0}
copy_file: ('src/tessumod/utils.py', 'build/lib.linux-x86_64-2.7/tessumod/utils.py') {'preserve_mode': 0}
copy_file: ('src/tessumod/resources.py', 'build/lib.linux-x86_64-2.7/tessumod/resources.py') {'preserve_mode': 0}
copy_file: ('src/tessumod/statemachine.py', 'build/lib.linux-x86_64-2.7/tessumod/statemachine.py') {'preserve_mode': 0}
copy_file: ('src/tessumod/http.py', 'build/lib.linux-x86_64-2.7/tessumod/http.py') {'preserve_mode': 0}
copy_file: ('src/tessumod/clientquery.py', 'build/lib.linux-x86_64-2.7/tessumod/clientquery.py') {'preserve_mode': 0}
copy_file: ('src/tessumod/notifications.py', 'build/lib.linux-x86_64-2.7/tessumod/notifications.py') {'preserve_mode': 0}
copy_file: ('src/tessumod/mytsplugin.py', 'build/lib.linux-x86_64-2.7/tessumod/mytsplugin.py') {'preserve_mode': 0}
copy_file: ('src/tessumod/settings.py', 'build/lib.linux-x86_64-2.7/tessumod/settings.py') {'preserve_mode': 0}
copy_file: ('src/tessumod/asyncore_utils.py', 'build/lib.linux-x86_64-2.7/tessumod/asyncore_utils.py') {'preserve_mode': 0}
copy_file: ('src/tessumod/async.py', 'build/lib.linux-x86_64-2.7/tessumod/async.py') {'preserve_mode': 0}
copy_file: ('src/tessumod/__init__.py', 'build/lib.linux-x86_64-2.7/tessumod/__init__.py') {'preserve_mode': 0}
installing to build/bdist.linux-x86_64/wotmod
running install
running install_lib
creating build/bdist.linux-x86_64/wotmod
creating build/bdist.linux-x86_64/wotmod/res
creating build/bdist.linux-x86_64/wotmod/res/scripts
creating build/bdist.linux-x86_64/wotmod/res/scripts/client
creating build/bdist.linux-x86_64/wotmod/res/scripts/client/gui
creating build/bdist.linux-x86_64/wotmod/res/scripts/client/gui/mods
creating build/bdist.linux-x86_64/wotmod/res/scripts/client/gui/mods/tessumod
copying build/lib.linux-x86_64-2.7/tessumod/user_cache.py -> build/bdist.linux-x86_64/wotmod/res/scripts/client/gui/mods/tessumod
copying build/lib.linux-x86_64-2.7/tessumod/ts3.py -> build/bdist.linux-x86_64/wotmod/res/scripts/client/gui/mods/tessumod
copying build/lib.linux-x86_64-2.7/tessumod/keyvaluestorage.py -> build/bdist.linux-x86_64/wotmod/res/scripts/client/gui/mods/tessumod
copying build/lib.linux-x86_64-2.7/tessumod/positional_audio.py -> build/bdist.linux-x86_64/wotmod/res/scripts/client/gui/mods/tessumod
copying build/lib.linux-x86_64-2.7/tessumod/utils.py -> build/bdist.linux-x86_64/wotmod/res/scripts/client/gui/mods/tessumod
copying build/lib.linux-x86_64-2.7/tessumod/resources.py -> build/bdist.linux-x86_64/wotmod/res/scripts/client/gui/mods/tessumod
copying build/lib.linux-x86_64-2.7/tessumod/statemachine.py -> build/bdist.linux-x86_64/wotmod/res/scripts/client/gui/mods/tessumod
copying build/lib.linux-x86_64-2.7/tessumod/build_info.py -> build/bdist.linux-x86_64/wotmod/res/scripts/client/gui/mods/tessumod
copying build/lib.linux-x86_64-2.7/tessumod/http.py -> build/bdist.linux-x86_64/wotmod/res/scripts/client/gui/mods/tessumod
copying build/lib.linux-x86_64-2.7/tessumod/clientquery.py -> build/bdist.linux-x86_64/wotmod/res/scripts/client/gui/mods/tessumod
copying build/lib.linux-x86_64-2.7/tessumod/notifications.py -> build/bdist.linux-x86_64/wotmod/res/scripts/client/gui/mods/tessumod
copying build/lib.linux-x86_64-2.7/tessumod/mytsplugin.py -> build/bdist.linux-x86_64/wotmod/res/scripts/client/gui/mods/tessumod
copying build/lib.linux-x86_64-2.7/tessumod/settings.py -> build/bdist.linux-x86_64/wotmod/res/scripts/client/gui/mods/tessumod
copying build/lib.linux-x86_64-2.7/tessumod/asyncore_utils.py -> build/bdist.linux-x86_64/wotmod/res/scripts/client/gui/mods/tessumod
copying build/lib.linux-x86_64-2.7/tessumod/async.py -> build/bdist.linux-x86_64/wotmod/res/scripts/client/gui/mods/tessumod
copying build/lib.linux-x86_64-2.7/tessumod/__init__.py -> build/bdist.linux-x86_64/wotmod/res/scripts/client/gui/mods/tessumod
copying build/lib.linux-x86_64-2.7/mod_tessumod.py -> build/bdist.linux-x86_64/wotmod/res/scripts/client/gui/mods
byte-compiling build/bdist.linux-x86_64/wotmod/res/scripts/client/gui/mods/tessumod/user_cache.py to user_cache.pyc
byte-compiling build/bdist.linux-x86_64/wotmod/res/scripts/client/gui/mods/tessumod/ts3.py to ts3.pyc
byte-compiling build/bdist.linux-x86_64/wotmod/res/scripts/client/gui/mods/tessumod/keyvaluestorage.py to keyvaluestorage.pyc
byte-compiling build/bdist.linux-x86_64/wotmod/res/scripts/client/gui/mods/tessumod/positional_audio.py to positional_audio.pyc
byte-compiling build/bdist.linux-x86_64/wotmod/res/scripts/client/gui/mods/tessumod/utils.py to utils.pyc
byte-compiling build/bdist.linux-x86_64/wotmod/res/scripts/client/gui/mods/tessumod/resources.py to resources.pyc
byte-compiling build/bdist.linux-x86_64/wotmod/res/scripts/client/gui/mods/tessumod/statemachine.py to statemachine.pyc
byte-compiling build/bdist.linux-x86_64/wotmod/res/scripts/client/gui/mods/tessumod/build_info.py to build_info.pyc
byte-compiling build/bdist.linux-x86_64/wotmod/res/scripts/client/gui/mods/tessumod/http.py to http.pyc
byte-compiling build/bdist.linux-x86_64/wotmod/res/scripts/client/gui/mods/tessumod/clientquery.py to clientquery.pyc
byte-compiling build/bdist.linux-x86_64/wotmod/res/scripts/client/gui/mods/tessumod/notifications.py to notifications.pyc
byte-compiling build/bdist.linux-x86_64/wotmod/res/scripts/client/gui/mods/tessumod/mytsplugin.py to mytsplugin.pyc
byte-compiling build/bdist.linux-x86_64/wotmod/res/scripts/client/gui/mods/tessumod/settings.py to settings.pyc
byte-compiling build/bdist.linux-x86_64/wotmod/res/scripts/client/gui/mods/tessumod/asyncore_utils.py to asyncore_utils.pyc
byte-compiling build/bdist.linux-x86_64/wotmod/res/scripts/client/gui/mods/tessumod/async.py to async.pyc
byte-compiling build/bdist.linux-x86_64/wotmod/res/scripts/client/gui/mods/tessumod/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/wotmod/res/scripts/client/gui/mods/mod_tessumod.py to mod_tessumod.pyc
running install_data
creating build/bdist.linux-x86_64/wotmod/res/mods
creating build/bdist.linux-x86_64/wotmod/res/mods/jhakonen.tessumod
copying data/checkbox_on.png -> build/bdist.linux-x86_64/wotmod/res/mods/jhakonen.tessumod
copying data/checkbox_off.png -> build/bdist.linux-x86_64/wotmod/res/mods/jhakonen.tessumod
copying data/ts_notification_icon.png -> build/bdist.linux-x86_64/wotmod/res/mods/jhakonen.tessumod
copying data/tsplugin_install_notification.json -> build/bdist.linux-x86_64/wotmod/res/mods/jhakonen.tessumod
copying data/tsplugin_update_notification.json -> build/bdist.linux-x86_64/wotmod/res/mods/jhakonen.tessumod
Writing build/bdist.linux-x86_64/wotmod/meta.xml
copying README.md -> build/bdist.linux-x86_64/wotmod
copying LICENSE.txt -> build/bdist.linux-x86_64/wotmod
creating '/home/jhakonen/git/tessumod/wot-teamspeak-mod/dist/jhakonen.tessumod_00.07.01.wotmod' and adding 'build/bdist.linux-x86_64/wotmod' to it
adding 'README.md'
adding 'LICENSE.txt'
adding 'meta.xml'
adding 'res/'
adding 'res/mods/'
adding 'res/scripts/'
adding 'res/mods/jhakonen.tessumod/'
adding 'res/mods/jhakonen.tessumod/tsplugin_install_notification.json'
adding 'res/mods/jhakonen.tessumod/tsplugin_update_notification.json'
adding 'res/mods/jhakonen.tessumod/checkbox_off.png'
adding 'res/mods/jhakonen.tessumod/ts_notification_icon.png'
adding 'res/mods/jhakonen.tessumod/checkbox_on.png'
adding 'res/scripts/client/'
adding 'res/scripts/client/gui/'
adding 'res/scripts/client/gui/mods/'
adding 'res/scripts/client/gui/mods/mod_tessumod.pyc'
adding 'res/scripts/client/gui/mods/mod_tessumod.py'
adding 'res/scripts/client/gui/mods/tessumod/'
adding 'res/scripts/client/gui/mods/tessumod/ts3.pyc'
adding 'res/scripts/client/gui/mods/tessumod/async.pyc'
adding 'res/scripts/client/gui/mods/tessumod/user_cache.py'
adding 'res/scripts/client/gui/mods/tessumod/ts3.py'
adding 'res/scripts/client/gui/mods/tessumod/keyvaluestorage.py'
adding 'res/scripts/client/gui/mods/tessumod/positional_audio.py'
adding 'res/scripts/client/gui/mods/tessumod/utils.py'
adding 'res/scripts/client/gui/mods/tessumod/build_info.pyc'
adding 'res/scripts/client/gui/mods/tessumod/mytsplugin.pyc'
adding 'res/scripts/client/gui/mods/tessumod/resources.py'
adding 'res/scripts/client/gui/mods/tessumod/user_cache.pyc'
adding 'res/scripts/client/gui/mods/tessumod/statemachine.pyc'
adding 'res/scripts/client/gui/mods/tessumod/statemachine.py'
adding 'res/scripts/client/gui/mods/tessumod/settings.pyc'
adding 'res/scripts/client/gui/mods/tessumod/build_info.py'
adding 'res/scripts/client/gui/mods/tessumod/asyncore_utils.pyc'
adding 'res/scripts/client/gui/mods/tessumod/http.py'
adding 'res/scripts/client/gui/mods/tessumod/positional_audio.pyc'
adding 'res/scripts/client/gui/mods/tessumod/__init__.pyc'
adding 'res/scripts/client/gui/mods/tessumod/clientquery.py'
adding 'res/scripts/client/gui/mods/tessumod/notifications.py'
adding 'res/scripts/client/gui/mods/tessumod/keyvaluestorage.pyc'
adding 'res/scripts/client/gui/mods/tessumod/mytsplugin.py'
adding 'res/scripts/client/gui/mods/tessumod/resources.pyc'
adding 'res/scripts/client/gui/mods/tessumod/clientquery.pyc'
adding 'res/scripts/client/gui/mods/tessumod/settings.py'
adding 'res/scripts/client/gui/mods/tessumod/asyncore_utils.py'
adding 'res/scripts/client/gui/mods/tessumod/http.pyc'
adding 'res/scripts/client/gui/mods/tessumod/async.py'
adding 'res/scripts/client/gui/mods/tessumod/utils.pyc'
adding 'res/scripts/client/gui/mods/tessumod/notifications.pyc'
adding 'res/scripts/client/gui/mods/tessumod/__init__.py'
removing 'build/bdist.linux-x86_64/wotmod' (and everything under it)
```
Try it out yourself, and follow how the build_info.py file gets generated, moved around, compiled and packaged. Does yours differ somehow from mine?

**Comment by Suvero** [comment]
<img width="1197" alt="Zrzut ekranu 2019-09-29 o 13 38 38" src="https://user-images.githubusercontent.com/44507538/65831904-7e2c3200-e2be-11e9-992a-e265ef8e84cb.png">
It's really strange - after added print to setup_helpers.py...

**Comment by Suvero** [comment]
`root@server465398:~/mod# ./setup.py bdist_wotmod
running bdist_wotmod
running build
running build_py
Generate in file: src/tessumod/build_info.py.in --> build/lib.linux-x86_64-2.7/tessumod/build_info.py
installing to build/bdist.linux-x86_64/wotmod
running install
running install_lib
creating build/bdist.linux-x86_64/wotmod
creating build/bdist.linux-x86_64/wotmod/res
creating build/bdist.linux-x86_64/wotmod/res/scripts
creating build/bdist.linux-x86_64/wotmod/res/scripts/client
creating build/bdist.linux-x86_64/wotmod/res/scripts/client/gui
creating build/bdist.linux-x86_64/wotmod/res/scripts/client/gui/mods
copying build/lib.linux-x86_64-2.7/mod_tessumod.pyc -> build/bdist.linux-x86_64/wotmod/res/scripts/client/gui/mods
creating build/bdist.linux-x86_64/wotmod/res/scripts/client/gui/mods/tessumod
copying build/lib.linux-x86_64-2.7/tessumod/asyncore_utils.pyc -> build/bdist.linux-x86_64/wotmod/res/scripts/client/gui/mods/tessumod
copying build/lib.linux-x86_64-2.7/tessumod/clientquery.py -> build/bdist.linux-x86_64/wotmod/res/scripts/client/gui/mods/tessumod
copying build/lib.linux-x86_64-2.7/tessumod/notifications.py -> build/bdist.linux-x86_64/wotmod/res/scripts/client/gui/mods/tessumod
copying build/lib.linux-x86_64-2.7/tessumod/resources.pyc -> build/bdist.linux-x86_64/wotmod/res/scripts/client/gui/mods/tessumod
copying build/lib.linux-x86_64-2.7/tessumod/async.py -> build/bdist.linux-x86_64/wotmod/res/scripts/client/gui/mods/tessumod
copying build/lib.linux-x86_64-2.7/tessumod/__init__.py -> build/bdist.linux-x86_64/wotmod/res/scripts/client/gui/mods/tessumod
copying build/lib.linux-x86_64-2.7/tessumod/settings.py -> build/bdist.linux-x86_64/wotmod/res/scripts/client/gui/mods/tessumod
copying build/lib.linux-x86_64-2.7/tessumod/async.pyc -> build/bdist.linux-x86_64/wotmod/res/scripts/client/gui/mods/tessumod
copying build/lib.linux-x86_64-2.7/tessumod/keyvaluestorage.py -> build/bdist.linux-x86_64/wotmod/res/scripts/client/gui/mods/tessumod
copying build/lib.linux-x86_64-2.7/tessumod/ts3.py -> build/bdist.linux-x86_64/wotmod/res/scripts/client/gui/mods/tessumod
copying build/lib.linux-x86_64-2.7/tessumod/mytsplugin.py -> build/bdist.linux-x86_64/wotmod/res/scripts/client/gui/mods/tessumod
copying build/lib.linux-x86_64-2.7/tessumod/__init__.pyc -> build/bdist.linux-x86_64/wotmod/res/scripts/client/gui/mods/tessumod
copying build/lib.linux-x86_64-2.7/tessumod/clientquery.pyc -> build/bdist.linux-x86_64/wotmod/res/scripts/client/gui/mods/tessumod
copying build/lib.linux-x86_64-2.7/tessumod/mytsplugin.pyc -> build/bdist.linux-x86_64/wotmod/res/scripts/client/gui/mods/tessumod
copying build/lib.linux-x86_64-2.7/tessumod/asyncore_utils.py -> build/bdist.linux-x86_64/wotmod/res/scripts/client/gui/mods/tessumod
copying build/lib.linux-x86_64-2.7/tessumod/resources.py -> build/bdist.linux-x86_64/wotmod/res/scripts/client/gui/mods/tessumod
copying build/lib.linux-x86_64-2.7/tessumod/notifications.pyc -> build/bdist.linux-x86_64/wotmod/res/scripts/client/gui/mods/tessumod
copying build/lib.linux-x86_64-2.7/tessumod/http.pyc -> build/bdist.linux-x86_64/wotmod/res/scripts/client/gui/mods/tessumod
copying build/lib.linux-x86_64-2.7/tessumod/user_cache.py -> build/bdist.linux-x86_64/wotmod/res/scripts/client/gui/mods/tessumod
copying build/lib.linux-x86_64-2.7/tessumod/utils.pyc -> build/bdist.linux-x86_64/wotmod/res/scripts/client/gui/mods/tessumod
copying build/lib.linux-x86_64-2.7/tessumod/settings.pyc -> build/bdist.linux-x86_64/wotmod/res/scripts/client/gui/mods/tessumod
copying build/lib.linux-x86_64-2.7/tessumod/utils.py -> build/bdist.linux-x86_64/wotmod/res/scripts/client/gui/mods/tessumod
copying build/lib.linux-x86_64-2.7/tessumod/user_cache.pyc -> build/bdist.linux-x86_64/wotmod/res/scripts/client/gui/mods/tessumod
copying build/lib.linux-x86_64-2.7/tessumod/ts3.pyc -> build/bdist.linux-x86_64/wotmod/res/scripts/client/gui/mods/tessumod
copying build/lib.linux-x86_64-2.7/tessumod/keyvaluestorage.pyc -> build/bdist.linux-x86_64/wotmod/res/scripts/client/gui/mods/tessumod
copying build/lib.linux-x86_64-2.7/tessumod/positional_audio.py -> build/bdist.linux-x86_64/wotmod/res/scripts/client/gui/mods/tessumod
copying build/lib.linux-x86_64-2.7/tessumod/positional_audio.pyc -> build/bdist.linux-x86_64/wotmod/res/scripts/client/gui/mods/tessumod
copying build/lib.linux-x86_64-2.7/tessumod/build_info.py -> build/bdist.linux-x86_64/wotmod/res/scripts/client/gui/mods/tessumod
copying build/lib.linux-x86_64-2.7/tessumod/http.py -> build/bdist.linux-x86_64/wotmod/res/scripts/client/gui/mods/tessumod
copying build/lib.linux-x86_64-2.7/tessumod/statemachine.pyc -> build/bdist.linux-x86_64/wotmod/res/scripts/client/gui/mods/tessumod
copying build/lib.linux-x86_64-2.7/tessumod/statemachine.py -> build/bdist.linux-x86_64/wotmod/res/scripts/client/gui/mods/tessumod
copying build/lib.linux-x86_64-2.7/mod_tessumod.py -> build/bdist.linux-x86_64/wotmod/res/scripts/client/gui/mods
running install_data
creating build/bdist.linux-x86_64/wotmod/res/mods
creating build/bdist.linux-x86_64/wotmod/res/mods/jhakonen.tessumod
copying data/checkbox_on.png -> build/bdist.linux-x86_64/wotmod/res/mods/jhakonen.tessumod
copying data/checkbox_off.png -> build/bdist.linux-x86_64/wotmod/res/mods/jhakonen.tessumod
copying data/ts_notification_icon.png -> build/bdist.linux-x86_64/wotmod/res/mods/jhakonen.tessumod
copying data/tsplugin_install_notification.json -> build/bdist.linux-x86_64/wotmod/res/mods/jhakonen.tessumod
copying data/tsplugin_update_notification.json -> build/bdist.linux-x86_64/wotmod/res/mods/jhakonen.tessumod
Writing build/bdist.linux-x86_64/wotmod/meta.xml
copying README.md -> build/bdist.linux-x86_64/wotmod
copying LICENSE.txt -> build/bdist.linux-x86_64/wotmod
creating '/root/mod/dist/jhakonen.tessumod_00.07.01.wotmod' and adding 'build/bdist.linux-x86_64/wotmod' to it
adding 'README.md'
adding 'LICENSE.txt'
adding 'meta.xml'
adding 'res/'
adding 'res/scripts/'
adding 'res/mods/'
adding 'res/scripts/client/'
adding 'res/scripts/client/gui/'
adding 'res/scripts/client/gui/mods/'
adding 'res/scripts/client/gui/mods/mod_tessumod.pyc'
adding 'res/scripts/client/gui/mods/mod_tessumod.py'
adding 'res/scripts/client/gui/mods/tessumod/'
adding 'res/scripts/client/gui/mods/tessumod/asyncore_utils.pyc'
adding 'res/scripts/client/gui/mods/tessumod/clientquery.py'
adding 'res/scripts/client/gui/mods/tessumod/notifications.py'
adding 'res/scripts/client/gui/mods/tessumod/resources.pyc'
adding 'res/scripts/client/gui/mods/tessumod/async.py'
adding 'res/scripts/client/gui/mods/tessumod/__init__.py'
adding 'res/scripts/client/gui/mods/tessumod/settings.py'
adding 'res/scripts/client/gui/mods/tessumod/async.pyc'
adding 'res/scripts/client/gui/mods/tessumod/keyvaluestorage.py'
adding 'res/scripts/client/gui/mods/tessumod/ts3.py'
adding 'res/scripts/client/gui/mods/tessumod/mytsplugin.py'
adding 'res/scripts/client/gui/mods/tessumod/__init__.pyc'
adding 'res/scripts/client/gui/mods/tessumod/clientquery.pyc'
adding 'res/scripts/client/gui/mods/tessumod/mytsplugin.pyc'
adding 'res/scripts/client/gui/mods/tessumod/asyncore_utils.py'
adding 'res/scripts/client/gui/mods/tessumod/resources.py'
adding 'res/scripts/client/gui/mods/tessumod/notifications.pyc'
adding 'res/scripts/client/gui/mods/tessumod/http.pyc'
adding 'res/scripts/client/gui/mods/tessumod/user_cache.py'
adding 'res/scripts/client/gui/mods/tessumod/utils.pyc'
adding 'res/scripts/client/gui/mods/tessumod/settings.pyc'
adding 'res/scripts/client/gui/mods/tessumod/utils.py'
adding 'res/scripts/client/gui/mods/tessumod/user_cache.pyc'
adding 'res/scripts/client/gui/mods/tessumod/ts3.pyc'
adding 'res/scripts/client/gui/mods/tessumod/keyvaluestorage.pyc'
adding 'res/scripts/client/gui/mods/tessumod/positional_audio.py'
adding 'res/scripts/client/gui/mods/tessumod/positional_audio.pyc'
adding 'res/scripts/client/gui/mods/tessumod/build_info.py'
adding 'res/scripts/client/gui/mods/tessumod/http.py'
adding 'res/scripts/client/gui/mods/tessumod/statemachine.pyc'
adding 'res/scripts/client/gui/mods/tessumod/statemachine.py'
adding 'res/mods/jhakonen.tessumod/'
adding 'res/mods/jhakonen.tessumod/checkbox_on.png'
adding 'res/mods/jhakonen.tessumod/ts_notification_icon.png'
adding 'res/mods/jhakonen.tessumod/tsplugin_install_notification.json'
adding 'res/mods/jhakonen.tessumod/tsplugin_update_notification.json'
adding 'res/mods/jhakonen.tessumod/checkbox_off.png'
removing 'build/bdist.linux-x86_64/wotmod' (and everything under it)`

I got it.

**Comment by jhakonen** [comment]
Hmm, looks like the pyc compiling step is skipped as I don't see any lines starting with "byte-compiling".

Can you check what version you have of setuptools and pip?
```
$ pip list | grep setuptools
setuptools                         41.0.1
$ pip list | grep pip
pip                                18.1
```
If you have significantly older versions installed, you could try upgrading them.
Another thing to try is to remove the `.eggs` folder, in case you have wrong version of bdist_wotmod  installed.

**Comment by Suvero** [comment]
<img width="287" alt="Zrzut ekranu 2019-09-29 o 15 11 17" src="https://user-images.githubusercontent.com/44507538/65832978-6909d000-e2cb-11e9-884e-319e60fac45a.png">
+ removed .eggs folder

Result ? Nothing happens. Still 296kb and still not working.
Maybe I'll give ip/pass to my ssh and You'll try it on my OS. What You think ? It is clear vps rented only for this modification.

**Comment by jhakonen** [comment]
Sure, we can do that too. Maybe send the credentials through email? You should be able too see mine from my profile page. Or from git history.

**Comment by Suvero** [comment]
Oh bro ! After try on other OS, it now compiling perfectly. I used on Ubuntu (latest) and now I tried on Debian latest too.. on debian works great. Thanks for support but now I have error with teamspeak plugin so I going to wot-teamspeak-plugin thread :)
