### ISSUE TITLE
Since Last TS3 Update Error after Tessumod is installed.

### ISSUE THREAD

**Issue by maestroat** [jhakonen/wot-teamspeak-mod#35]
when i connect to a server ts3 crashed

Sent: 16384/95431 bytes
Sent: 95431/95431 bytes
Error: 201
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Invalid according to Policy: Policy expired.</Message><RequestId>2E1E665ABE8A8CED</RequestId><HostId>iV7LPubDj3rcSmGD/O29J5QZ6xCOJXMVu9K9mdUJIaqhnGUevXpThz99jhABI+nNToQn8w5xyTY=</HostId></Error>

**Comment by Bealze** [comment]
mine crashes the game when linked

**Comment by Donnervogel39** [comment]
Habe das selbe Problem. Wenn ich das Plug In installiert habe stürzt der Teamspeak ab. Ich dachte erst es läge am Mod für WoT. Aber der TS stürzt auch ab wenn der Mod nicht installiert ist. Bitte um Hilfe!!!!

**Comment by jhakonen** [comment]
I think I managed to fix the crash. Could you verify that it works?

Here's a link to a test build with the fix in place:
https://github.com/jhakonen/wot-teamspeak-plugin/suites/676321591/artifacts/6173618 (requires login to Github, returns 404 otherwise)

**Comment by jhakonen** [comment]
No reply. I assume that this is fixed then. Closing ticket.
