### ISSUE TITLE
Tessumod Plug In funktioniert nicht mehr!!!

### ISSUE THREAD

**Issue by Donnervogel39** [jhakonen/wot-teamspeak-mod#36]
Seit einigen Tagen stürzt der Teamspeak ab wenn das Tessumod Plug In installiert ist. Ich dachte erst es läge am WoT-Mod. Doch der TS stürzt auch ab wenn der Mod nicht installiert ist. Ich habe alle Programme schon neu installiert. Aber es funktioniert leider trotzdem nicht. Ich bitte um Antwort ob das Plug In überarbeitet wird. Oder um Informationen wie ich den Fehler vielleicht selber beheben kann.

**Comment by jhakonen** [comment]
Yea, I think it is because in the new TS3 version, its plugin API has changed, and the problem might be because of that. I've reproduced it locally, and it sure is crashing. Unfortunately I haven't had time yet to figure out what is going wrong.

Busy at the moment trying to setup build pipeline for the plugin: https://github.com/jhakonen/actions-test/actions

**Comment by Donnervogel39** [comment]
Thank you for your prompt reply. I hope it will work again soon. It is a very good plug-in and very useful.

**Comment by jhakonen** [comment]
I think I managed to fix the crash. Could you verify that it works?

Here's a link to a test build with the fix in place:
https://github.com/jhakonen/wot-teamspeak-plugin/suites/676321591/artifacts/6173618 (requires login to Github, returns 404 otherwise)

**Comment by Donnervogel39** [comment]
I have only been able to test it briefly. But I can say that there was no longer a crash. I will test it again longer this afternoon. Also whether it remains stable with WoT over a longer period of time. In any case, I would like to thank you for fixing the error so quickly.

**Comment by jhakonen** [comment]
Thank you, yeah please test it more thoroughly if you can. I'll try to make a new release right after if it looks good.

**Comment by Donnervogel39** [comment]
Hi,
I have now tested it again for a longer time and it worked without problems for me. I think you can publish it.

**Comment by jhakonen** [comment]
Will do, thanks for help!

**Comment by Donnervogel39** [comment]
You are welcome. It was useful for me too.
