### ISSUE TITLE
Tank class icon goes white after been replaced by speaker icon

### ISSUE THREAD

**Issue by jhakonen** [jhakonen/wot-teamspeak-mod#8]
Originally reported by rdcl_be:
http://forum.worldoftanks.eu/index.php?/topic/433614-094-tessumod-wotteamspeak-integration-mod-v034-5112014/page__st__80__pid__9402472#entry9402472

**Comment by 2case** [comment]
Didn't not that for a while. Still a bug?

**Comment by jhakonen** [comment]
I haven't seen anyone report this lately, so I assume this isn't a problem anymore. Closing.
